export const COUNTRIES = {
	"US": { name: "United States", lat: 37, lon: -95, keywords: ["USA", "United States", "Washington", "Biden", "Trump", "Wall Street"], domains: ["nytimes.com", "washingtonpost.com", "cnn.com", "foxnews.com", "nbcnews.com", "usatoday.com"] },
	"GB": { name: "United Kingdom", lat: 55, lon: -3, keywords: ["UK", "United Kingdom", "London", "Britain", "Parliament", "Downing Street"], domains: ["bbc.co.uk", "theguardian.com", "independent.co.uk", "telegraph.co.uk", "dailymail.co.uk"] },
	"FR": { name: "France", lat: 46, lon: 2, keywords: ["France", "Paris", "Macron", "French"], domains: ["lemonde.fr", "lefigaro.fr", "france24.com"] },
	"DE": { name: "Germany", lat: 51, lon: 9, keywords: ["Germany", "Berlin", "Scholz", "German"], domains: ["dw.com", "spiegel.de", "zeit.de"] },
	"CN": { name: "China", lat: 35, lon: 105, keywords: ["China", "Beijing", "Xi Jinping", "Chinese"], domains: ["xinhuanet.com", "chinadaily.com.cn", "scmp.com"] },
	"IN": { name: "India", lat: 20, lon: 78, keywords: ["India", "New Delhi", "Modi", "Indian"], domains: ["timesofindia.indiatimes.com", "thehindu.com", "ndtv.com", "business-standard.com"] },
	"JP": { name: "Japan", lat: 36, lon: 138, keywords: ["Japan", "Tokyo", "Japanese", "Kishida"], domains: ["asahi.com", "mainichi.jp", "japantimes.co.jp"] },
	"RU": { name: "Russia", lat: 61, lon: 105, keywords: ["Russia", "Moscow", "Putin", "Russian", "Kremlin"], domains: ["rt.com", "tass.com"] },
	"BR": { name: "Brazil", lat: -14, lon: -51, keywords: ["Brazil", "Brasilia", "Lula", "Brazilian"], domains: ["globo.com", "uol.com.br"] },
	"AU": { name: "Australia", lat: -25, lon: 133, keywords: ["Australia", "Canberra", "Australian"], domains: ["abc.net.au", "theage.com.au", "smh.com.au"] },
	"CA": { name: "Canada", lat: 60, lon: -95, keywords: ["Canada", "Ottawa", "Trudeau", "Canadian"], domains: ["cbc.ca", "thestar.com", "globeandmail.com"] },
	"IT": { name: "Italy", lat: 42, lon: 12, keywords: ["Italy", "Rome", "Italian", "Meloni"], domains: ["corriere.it", "repubblica.it"] },
	"ES": { name: "Spain", lat: 40, lon: -3, keywords: ["Spain", "Madrid", "Spanish"], domains: ["elpais.com", "elmundo.es"] },
	"UA": { name: "Ukraine", lat: 49, lon: 31, keywords: ["Ukraine", "Kyiv", "Zelenskyy", "Ukrainian"], domains: ["kyivindependent.com", "ukrinform.net"] },
	"IL": { name: "Israel", lat: 31, lon: 35, keywords: ["Israel", "Jerusalem", "Tel Aviv", "Netanyahu"], domains: ["haaretz.com", "jpost.com", "timesofisrael.com"] },
	"ZA": { name: "South Africa", lat: -29, lon: 24, keywords: ["South Africa", "Pretoria", "Johannesburg", "Cape Town"], domains: ["news24.com", "dailymaverick.co.za"] },
	"KR": { name: "South Korea", lat: 36, lon: 127, keywords: ["South Korea", "Seoul", "Korean"], domains: ["yna.co.kr", "koreaherald.com"] },
	"SA": { name: "Saudi Arabia", lat: 24, lon: 45, keywords: ["Saudi Arabia", "Riyadh", "Saudi"], domains: ["arabnews.com", "alriyadh.com"] },
	"EG": { name: "Egypt", lat: 26, lon: 30, keywords: ["Egypt", "Cairo", "Egyptian"], domains: ["ahram.org.eg"] },
	"MX": { name: "Mexico", lat: 23, lon: -102, keywords: ["Mexico", "Mexico City", "Mexican"], domains: ["eluniversal.com.mx", "reforma.com"] },
};
